# Generated by Django 4.2.7 on 2025-11-26 20:51

import apps.assets.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('Camión Supersucker', 'Camión Supersucker'), ('Camioneta MDO', 'Camioneta MDO'), ('Retroexcavadora MDO', 'Retroexcavadora MDO'), ('Cargador Frontal MDO', 'Cargador Frontal MDO'), ('Minicargador MDO', 'Minicargador MDO')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9\\-]+$')])),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='License plate must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9\\-]+$')])),
                ('installation_date', models.DateField()),
                ('status', models.CharField(choices=[('Operando', 'Operando'), ('Detenida', 'Detenida'), ('En Mantenimiento', 'En Mantenimiento'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Operando', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('coordinates', models.CharField(blank=True, help_text='Lat,Long format', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('manual', 'Manual'), ('certificate', 'Certificado'), ('invoice', 'Factura'), ('photo', 'Fotografía'), ('other', 'Otro')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='assets/documents/%Y/%m/', validators=[apps.assets.validators.validate_document_file])),
                ('description', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
                'db_table': 'asset_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
