# Generated by Django 4.2.7 on 2025-11-26 23:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Parte')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('min_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('unit_of_measure', models.CharField(default='unidad', max_length=50, verbose_name='Unidad de Medida')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación de Almacenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'spare_parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUSTMENT', 'Ajuste'), ('RETURN', 'Devolución'), ('TRANSFER', 'Transferencia'), ('INITIAL', 'Inventario Inicial')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('quantity_before', models.IntegerField(verbose_name='Cantidad Anterior')),
                ('quantity_after', models.IntegerField(verbose_name='Cantidad Posterior')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Referencia')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.sparepart', verbose_name='Repuesto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spare_part', '-created_at'], name='stock_movem_spare_p_638f64_idx'), models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'), models.Index(fields=['user'], name='stock_movem_user_id_4fa986_idx'), models.Index(fields=['-created_at'], name='stock_movem_created_8de937_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['part_number'], name='spare_parts_part_nu_98a1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['name'], name='spare_parts_name_c3eb78_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category'], name='spare_parts_categor_e0472e_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['is_active'], name='spare_parts_is_acti_46d0df_idx'),
        ),
    ]
