# Generated by Django 4.2.7 on 2025-11-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
