# Generated by Django 4.2.7 on 2025-11-27 21:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('model_type', models.CharField(default='RANDOM_FOREST', max_length=50)),
                ('model_file_path', models.CharField(max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('encoder_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('training_data_size', models.IntegerField()),
                ('training_duration_seconds', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('feature_importance', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_production', models.BooleanField(default=False)),
                ('hyperparameters', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('active_work_orders', models.IntegerField(default=0)),
                ('estimated_hours_remaining', models.FloatField(default=0.0)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.location')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operator availabilities',
                'db_table': 'operator_availability',
            },
        ),
        migrations.CreateModel(
            name='OperatorSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_category', models.CharField(choices=[('VEHICLE_TYPE', 'Vehicle Type'), ('MAINTENANCE_TASK', 'Maintenance Task'), ('TOOL', 'Tool/Equipment'), ('SAFETY', 'Safety Certification')], max_length=50)),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(help_text='1=Beginner, 5=Expert', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_certified', models.BooleanField(default=False)),
                ('certification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('average_completion_time', models.FloatField(blank=True, help_text='Average hours to complete tasks', null=True)),
                ('success_rate', models.FloatField(default=100.0, help_text='Percentage of successful completions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('acquired_date', models.DateField(auto_now_add=True)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_skills',
                'ordering': ['operator', 'skill_category', 'skill_name'],
                'unique_together': {('operator', 'skill_category', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='OperatorPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('work_orders_completed', models.IntegerField(default=0)),
                ('total_hours_worked', models.FloatField(default=0.0)),
                ('average_completion_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=100.0)),
                ('rework_count', models.IntegerField(default=0)),
                ('customer_satisfaction', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('performance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_performance',
                'ordering': ['-period_end'],
                'unique_together': {('operator', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='FailurePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('failure_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=20)),
                ('predicted_failure_type', models.CharField(blank=True, max_length=100)),
                ('estimated_days_to_failure', models.IntegerField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('features_snapshot', models.JSONField(default=dict)),
                ('recommended_action', models.TextField(blank=True)),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_failure_occurred', models.BooleanField(blank=True, null=True)),
                ('actual_failure_date', models.DateTimeField(blank=True, null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='assets.asset')),
                ('work_order_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggering_prediction', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'failure_predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['asset', '-prediction_date'], name='failure_pre_asset_i_920198_idx'), models.Index(fields=['risk_level'], name='failure_pre_risk_le_dfc1f1_idx'), models.Index(fields=['failure_probability'], name='failure_pre_failure_f4f944_idx')],
            },
        ),
    ]
