# Generated by Django 4.2.7 on 2025-12-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT chileno sin puntos ni guión', max_length=12),
        ),
    ]
