# Generated by Django 4.2.7 on 2025-11-26 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recurrence_type', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual'), ('Por Horas', 'Por Horas de Uso'), ('Por Kilómetros', 'Por Kilómetros')], max_length=50)),
                ('recurrence_interval', models.IntegerField(default=1, help_text='Intervalo de recurrencia (ej: cada 2 semanas, cada 3 meses)')),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('usage_threshold', models.IntegerField(blank=True, help_text='Umbral de uso para mantenimiento (horas o kilómetros)', null=True)),
                ('last_usage_value', models.IntegerField(blank=True, help_text='Último valor de uso registrado', null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Duración estimada del mantenimiento en horas', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Pausado', 'Pausado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=50)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_plans', to=settings.AUTH_USER_MODEL)),
                ('paused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_maintenance_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Plan',
                'verbose_name_plural': 'Maintenance Plans',
                'db_table': 'maintenance_plans',
                'ordering': ['next_due_date', '-created_at'],
                'indexes': [models.Index(fields=['asset'], name='maintenance_asset_i_674acc_idx'), models.Index(fields=['status'], name='maintenance_status_d5eb4f_idx'), models.Index(fields=['next_due_date'], name='maintenance_next_du_7c6bd7_idx'), models.Index(fields=['recurrence_type'], name='maintenance_recurre_724d6e_idx')],
            },
        ),
    ]
