# Generated by Django 4.2.7 on 2025-11-27 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_type', models.CharField(max_length=50)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_level', models.IntegerField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets.asset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Status History',
                'verbose_name_plural': 'Asset Status Histories',
                'db_table': 'asset_status_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='asset_statu_asset_i_052389_idx'), models.Index(fields=['status_type'], name='asset_statu_status__834bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_type', models.CharField(choices=[('OPERANDO', 'Operando'), ('DETENIDA', 'Detenida'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio')], default='OPERANDO', max_length=50)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer or hour meter reading', max_digits=10, null=True)),
                ('fuel_level', models.IntegerField(blank=True, help_text='Fuel level percentage (0-100)', null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='assets.asset')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Status',
                'verbose_name_plural': 'Asset Statuses',
                'db_table': 'asset_status',
                'indexes': [models.Index(fields=['asset'], name='asset_statu_asset_i_9db32c_idx'), models.Index(fields=['status_type'], name='asset_statu_status__9e12d4_idx')],
            },
        ),
    ]
