# Generated by Django 4.2.7 on 2025-11-27 00:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('vehicle_type', models.CharField(choices=[('CAMION_SUPERSUCKER', 'Camión Supersucker'), ('CAMIONETA_MDO', 'Camioneta MDO'), ('RETROEXCAVADORA_MDO', 'Retroexcavadora MDO'), ('CARGADOR_FRONTAL_MDO', 'Cargador Frontal MDO'), ('MINICARGADOR_MDO', 'Minicargador MDO')], max_length=50, verbose_name='Tipo de Vehículo')),
                ('is_system_template', models.BooleanField(default=False, verbose_name='Plantilla del Sistema')),
                ('passing_score', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntuación Mínima (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Plantilla de Checklist',
                'verbose_name_plural': 'Plantillas de Checklists',
                'db_table': 'checklist_templates',
                'ordering': ['vehicle_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200, verbose_name='Sección')),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('response_type', models.CharField(choices=[('yes_no_na', 'Sí / No / No Aplica'), ('text', 'Texto Libre'), ('numeric', 'Valor Numérico'), ('photo', 'Foto Requerida')], default='yes_no_na', max_length=20, verbose_name='Tipo de Respuesta')),
                ('required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('observations_allowed', models.BooleanField(default=True, verbose_name='Permite Observaciones')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Item de Plantilla',
                'verbose_name_plural': 'Items de Plantilla',
                'db_table': 'checklist_template_items',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntuación (%)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='IN_PROGRESS', max_length=20, verbose_name='Estado')),
                ('signature_data', models.TextField(blank=True, verbose_name='Firma Digital')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='checklists/pdfs/%Y/%m/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='assets.asset', verbose_name='Activo')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completado Por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklisttemplate', verbose_name='Plantilla')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses', to='work_orders.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Respuesta de Checklist',
                'verbose_name_plural': 'Respuestas de Checklists',
                'db_table': 'checklist_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.CharField(blank=True, max_length=50, verbose_name='Valor de Respuesta')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checklists/photos/%Y/%m/', verbose_name='Foto')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Respuesta')),
                ('checklist_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='checklists.checklistresponse', verbose_name='Respuesta de Checklist')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklisttemplateitem', verbose_name='Item de Plantilla')),
            ],
            options={
                'verbose_name': 'Respuesta de Item',
                'verbose_name_plural': 'Respuestas de Items',
                'db_table': 'checklist_item_responses',
                'ordering': ['checklist_response', 'template_item__order'],
            },
        ),
        migrations.AddIndex(
            model_name='checklisttemplateitem',
            index=models.Index(fields=['template', 'order'], name='checklist_t_templat_5603bd_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['code'], name='checklist_t_code_858f27_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['vehicle_type'], name='checklist_t_vehicle_eac5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_system_template'], name='checklist_t_is_syst_efb56a_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_active'], name='checklist_t_is_acti_33f037_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['asset', '-created_at'], name='checklist_r_asset_i_29e387_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['work_order'], name='checklist_r_work_or_e4553e_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['completed_by'], name='checklist_r_complet_96b6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['status'], name='checklist_r_status_3f494c_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['-created_at'], name='checklist_r_created_b64138_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitemresponse',
            index=models.Index(fields=['checklist_response'], name='checklist_i_checkli_da98cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitemresponse',
            unique_together={('checklist_response', 'template_item')},
        ),
    ]
