# Generated by Django 4.2.7 on 2025-12-16 19:15

from django.db import migrations, models


def update_vehicle_type_values(apps, schema_editor):
    """Update vehicle type values to match Asset model."""
    ChecklistTemplate = apps.get_model('checklists', 'ChecklistTemplate')
    
    # Mapping from old values to new values
    value_mapping = {
        'CAMION_SUPERSUCKER': 'Camión Supersucker',
        'CAMIONETA_MDO': 'Camioneta MDO',
        'RETROEXCAVADORA_MDO': 'Retroexcavadora MDO',
        'CARGADOR_FRONTAL_MDO': 'Cargador Frontal MDO',
        'MINICARGADOR_MDO': 'Minicargador MDO',
    }
    
    for template in ChecklistTemplate.objects.all():
        if template.vehicle_type in value_mapping:
            template.vehicle_type = value_mapping[template.vehicle_type]
            template.save()


def reverse_vehicle_type_values(apps, schema_editor):
    """Reverse the vehicle type values back to constants."""
    ChecklistTemplate = apps.get_model('checklists', 'ChecklistTemplate')
    
    # Reverse mapping
    reverse_mapping = {
        'Camión Supersucker': 'CAMION_SUPERSUCKER',
        'Camioneta MDO': 'CAMIONETA_MDO',
        'Retroexcavadora MDO': 'RETROEXCAVADORA_MDO',
        'Cargador Frontal MDO': 'CARGADOR_FRONTAL_MDO',
        'Minicargador MDO': 'MINICARGADOR_MDO',
    }
    
    for template in ChecklistTemplate.objects.all():
        if template.vehicle_type in reverse_mapping:
            template.vehicle_type = reverse_mapping[template.vehicle_type]
            template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='vehicle_type',
            field=models.CharField(choices=[('Camión Supersucker', 'Camión Supersucker'), ('Camioneta MDO', 'Camioneta MDO'), ('Retroexcavadora MDO', 'Retroexcavadora MDO'), ('Cargador Frontal MDO', 'Cargador Frontal MDO'), ('Minicargador MDO', 'Minicargador MDO')], max_length=50, verbose_name='Tipo de Vehículo'),
        ),
        migrations.RunPython(
            update_vehicle_type_values,
            reverse_vehicle_type_values,
        ),
    ]
