# Generated by Django 4.2.7 on 2025-12-01 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(help_text='Tipo de recurso accedido (workorder, asset, etc.)', max_length=100, verbose_name='Tipo de Recurso')),
                ('resource_id', models.CharField(help_text='ID del recurso específico', max_length=100, verbose_name='ID del Recurso')),
                ('action', models.CharField(help_text='Acción realizada (view, create, update, delete)', max_length=50, verbose_name='Acción')),
                ('success', models.BooleanField(default=True, help_text='Si el acceso fue exitoso o denegado', verbose_name='Éxito')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre el acceso', verbose_name='Detalles')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='access_logs_user_id_a657f9_idx'), models.Index(fields=['resource_type', 'resource_id'], name='access_logs_resourc_b5d576_idx'), models.Index(fields=['success', 'timestamp'], name='access_logs_success_0afacc_idx'), models.Index(fields=['timestamp'], name='access_logs_timesta_c3f10e_idx')],
            },
        ),
    ]
